### ISSUE TITLE
so it doesnt support web aplications??

### ISSUE THREAD

**Issue by sepehr13494** [fluttercandies/flutter_image_compress#111]

**Comment by CaiJingLong** [comment]
So far, flutter web is not supported.

**Comment by felixwortmann** [comment]
Is it planned to add web support? @CaiJingLong <br>
As flutter is expanding to more platforms I think it is important to have libraries like this one on as much platforms as possible.

**Comment by FRANIAZA** [comment]
Support for web would be very nice

**Comment by atleugim** [comment]
Any update on this?

**Comment by bismarabia** [comment]
Any updates?? @CaiJingLong

**Comment by CuongNV12** [comment]
I need it for web too, is there any plan to support it for web?

**Comment by c-seeger** [comment]
same here

**Comment by shkvoretz** [comment]
yip! That would be nice.
