### ISSUE TITLE
iOS build error (fatal error: module  'flutter_image_compress' not found )

### ISSUE THREAD

**Issue by john990** [fluttercandies/flutter_image_compress#188]
flutter_image_compress: ^1.1.0
Flutter (Channel stable, 2.2.2)

when run flutter build ios found this error:
```
/Users/kai/Developer/workspace/quick_scanner/ios/Runner/GeneratedPluginRegistrant.m:34:9: fatal error: module
    'flutter_image_compress' not found
    @import flutter_image_compress;
     ~~~~~~~^~~~~~~~~~~~~~~~~~~~~~
    1 error generated.
```

I have tried flutter clean, pod install --repo-update, Doesn't work.

[#182](https://github.com/OpenFlutter/flutter_image_compress/pull/182) also doesn't work. Has anyone encountered a similar problem?

**Comment by taoshotaro** [comment]
Changing `General > Deployment Info > iOS 9` in Xcode project might work. I changed mine to `iOS 12.0` which is same as my Podfile deployment target, and it worked.

**Comment by AryashDubey** [comment]
If you are using firebase then just try deleting the googleinfo.plist or just ensure that the file is correctly placed. That fixed the issue for me.

**Comment by john990** [comment]
> Changing `General > Deployment Info > iOS 9` in Xcode project might work. I changed mine to `iOS 12.0` which is same as my Podfile deployment target, and it worked.

Cool, You are right!!

**Comment by kalsariyac** [comment]
> Changing `General > Deployment Info > iOS 9` in Xcode project might work. I changed mine to `iOS 12.0` which is same as my Podfile deployment target, and it worked.

Yup, It's worked for me.
