### ISSUE TITLE
The Android Gradle plugin supports only kotlin-android-extensions Gradle plugin version 1.6.20 and higher.

### ISSUE THREAD

**Issue by sh4wn** [fluttercandies/flutter_image_compress#231]
with Android Studio 2021.3.1 Patch 1 and android gradle 7.3.1

```
The Android Gradle plugin supports only kotlin-android-extensions Gradle plugin version 1.6.20 and higher.
The following dependencies do not satisfy the required version:
project ':flutter_image_compress' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.6.10
```

**Comment by thePlayer094** [comment]
I am facing with same. Is there any solution available? 

gradle version : **classpath 'com.android.tools.build:gradle:7.4.1'**
gradle-wrapper.properties:   **distributionUrl=https\://services.gradle.org/distributions/gradle-7.5-all.zip**
