### ISSUE TITLE
2.0.4版本提示不支持kotlin-gradle-plugin:1.6.20 and higher. 请问有解决方案吗？

### ISSUE THREAD

**Issue by LeeCharry** [fluttercandies/flutter_image_compress#253]
### Content

报错 “The Android Gradle plugin supports only kotlin-android-extensions Gradle plugin version 1.6.20 and higher. The following dependencies do not satisfy the required version: project ':flutter_image_compress_common' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.6.10”

flutter-image-comress: 2.0.4
flutter-sdk: 3.10.3
AGP: 7.3.0
Grade: 7.4
kotlin: 1.7.10

**Comment by duypxd** [comment]
same issues

**Comment by pppshiwen** [comment]
same issues
