### ISSUE TITLE
[Discussions] does plan support android jdk 17 

### ISSUE THREAD

**Issue by Yongle-Fu** [fluttercandies/flutter_image_compress#270]

**Comment by Yongle-Fu** [comment]
* What went wrong:
Execution failed for task ':flutter_image_compress_common:compileDebugKotlin'.
> 'compileDebugJavaWithJavac' task (current target is 1.8) and 'compileDebugKotlin' task (current target is 17) jvm target compatibility should be set to the same Java version.
  Consider using JVM toolchain: https://kotl.in/gradle/jvm/toolchain

**Comment by VictorUvarov** [comment]
What changes to the plugin need to be made to fix this error?

**Comment by aly22** [comment]
It's still not working for me.

**Comment by alviazirin** [comment]
go into the plugin folder
inside the package folder, on flutter_image_compress_common, android folder, on build.gradle file, change the android block into this

`android {
    compileSdkVersion 34

    if (project.android.hasProperty("namespace")) {
        namespace 'com.fluttercandies.flutter_image_compress'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    kotlinOptions {
        jvmTarget = '1.8'
    }

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    defaultConfig {
        minSdkVersion 16
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }
}`

sadly this is just a stopgap solution, kinda like putting duct tape, run it, if it works then just build your app with this modification, if you want to keep the change persist, i recommend to just fork it and make modification, and sadly try to make it works with github url

**Comment by Mr-yuwei** [comment]
same problem

**Comment by FujiKinaga** [comment]
same too 🥺

**Comment by Ravensof** [comment]
temporary solution for issues like that:

```groovy
// android/build.gradle

subprojects {
    afterEvaluate {
        if (project.plugins.hasPlugin("com.android.application")
                || project.plugins.hasPlugin("com.android.library")) {

            // todo https://github.com/avioli/uni_links/issues/187
            if (project.name == "uni_links") {
                project.android.namespace = "name.avioli.unilinks"
            }

            // todo https://github.com/fluttercandies/flutter_image_compress/issues/270
            if (project.name == "flutter_image_compress_common") {
                project.android.compileOptions {
                    sourceCompatibility = JavaVersion.VERSION_17
                    targetCompatibility = JavaVersion.VERSION_17
                }
            }
        }
    }

    project.buildDir = "${rootProject.buildDir}/${project.name}"
    project.evaluationDependsOn(":app")
}
```

**Comment by Miracle-Blue** [comment]
https://github.com/fluttercandies/flutter_image_compress/issues/270#issuecomment-1868225821  - this is worked for me, please add this to library code

**Comment by romatallinn** [comment]
There are quite some PRs offered that should fix the problem.
https://github.com/fluttercandies/flutter_image_compress/pull/271, https://github.com/fluttercandies/flutter_image_compress/pull/275, https://github.com/fluttercandies/flutter_image_compress/pull/276

@CaiJingLong @basveenema @shomatan

**Comment by hunghuy201280** [comment]
any update?

**Comment by hunghuy201280** [comment]
here's temporary fix for this: 
```yaml
  flutter_image_compress:
    git:
      url: https://github.com/hunghuy201280/flutter_image_compress.git
      path: packages/flutter_image_compress
      ref: 79172bb
````

**Comment by rignaneseleo** [comment]
This is not fixed yet

**Comment by AlexV525** [comment]
The PR #289 includes JDK 17 rolling, the workflow runs with Java 17 and every job looks fine.
- https://github.com/fluttercandies/flutter_image_compress/pull/289/files
- https://github.com/fluttercandies/flutter_image_compress/actions/runs/8145725620/job/22262692279
