### ISSUE TITLE
[Bug report] Update js package to the latest version

### ISSUE THREAD

**Issue by TarasBounty** [fluttercandies/flutter_image_compress#285]
### Version

2.1.0

### Platforms

dart, Web

### Device Model

Any

### flutter info

```sh
Doesn't matter
```

### How to reproduce?

A lot of packages uses js ^0.7.0, so conflicts with this package

**Comment by TarasBounty** [comment]
@CaiJingLong

**Comment by TarasBounty** [comment]
> @CaiJingLong

@CaiJingLong please it's important for us

**Comment by mark8044** [comment]
Yes this is needed

**Comment by TarasBounty** [comment]
@CaiJingLong

**Comment by TarasBounty** [comment]
@AlexV525

**Comment by TarasBounty** [comment]
@CaiJingLong @AlexV525
