### ISSUE TITLE
是否有添加鸿蒙平台的打算呢

### ISSUE THREAD

**Issue by jinliyuelong** [fluttercandies/flutter_image_compress#290]
### Content

是否有添加鸿蒙平台的打算呢

**Comment by zmtzawqlp** [comment]
等待鸿蒙开放给个人开发者

**Comment by jinliyuelong** [comment]
[permission_handler_ohos](https://github.com/HarmonyCandies/permission_handler_ohos) 这个也是你开发的，应该有权限了吧。能否先支持一下beat版本

**Comment by jinliyuelong** [comment]
> 等待鸿蒙开放给个人开发者

[permission_handler_ohos](https://github.com/HarmonyCandies/permission_handler_ohos) 这个也是你开发的，应该有权限了吧。能否先支持一下beat版本

**Comment by zmtzawqlp** [comment]
> > 等待鸿蒙开放给个人开发者
> 
> [permission_handler_ohos](https://github.com/HarmonyCandies/permission_handler_ohos) 这个也是你开发的，应该有权限了吧。能否先支持一下beat版本

看是否有空余时间，希望有很多人能贡献 pr。

**Comment by zmtzawqlp** [comment]
done https://pub-web.flutter-io.cn/packages/flutter_image_compress
