### ISSUE TITLE
Migration to js_interop for WASM Compatibility

### ISSUE THREAD

**Issue by MominRaza** [fluttercandies/flutter_image_compress#297]
Migrate web plugin from the `js` package to `js_interop` and migrate `dart:html` to `package:web`.

**Comment by myxzlpltk** [comment]
I already add pull request here #306

**Comment by MominRaza** [comment]
Thanks
In your pr add "fixes #297"

**Comment by bhanuka96** [comment]
This issue has been open since April. Is this plugin discontinued?
